-- ============================================================================
-- 012_column_comments.sql
--
-- Purpose: describe every column in the database itself.
--
-- These COMMENT statements are the source of the Description column in
-- docs/database/DATA_DICTIONARY.md, which is generated by
-- tests/gen_data_dictionary.py rather than maintained by hand. Documenting the
-- column here means the dictionary cannot drift away from the schema: change a
-- column, change its comment beside it, regenerate.
--
-- They are also visible in psql (\d+ table) and in any GUI client, so the
-- explanation reaches whoever is looking at the data.
-- ============================================================================

-- Idempotent DROP IF EXISTS guards below emit "does not exist, skipping"
-- notices on a first run. They are harmless, but they read like failures to
-- someone running this for the first time, so notices are quietened here.
-- Warnings and errors still come through.
SET client_min_messages = warning;


-- --------------------------------------------------------------------- facility
COMMENT ON COLUMN facility.facility_id  IS 'Surrogate key.';
COMMENT ON COLUMN facility.name         IS 'Trading name; UNIQUE, so it is also a candidate key.';
COMMENT ON COLUMN facility.tax_rate_pct IS 'Percentage added to every bill raised here. Held on the facility, not on the bill: see NORMALIZATION.md 3NF(a).';
COMMENT ON COLUMN facility.opens_at     IS 'Local opening time. 00:00-23:59 for a 24 hour site.';
COMMENT ON COLUMN facility.is_active    IS 'FALSE retires a site without deleting its history.';

-- ------------------------------------------------------------------------ floor
COMMENT ON COLUMN floor.level_number IS 'Storey number. 0 is ground, negative values are basements. UNIQUE per facility.';
COMMENT ON COLUMN floor.name         IS 'Human label shown on the floor tabs, e.g. "Basement".';

-- ------------------------------------------------------------------------- zone
COMMENT ON COLUMN zone.code IS 'Single letter block identifier, unique within the floor. Used for aisle grouping on the slot map.';

-- ------------------------------------------------------------------------- slot
COMMENT ON COLUMN slot.slot_id         IS 'Surrogate key.';
COMMENT ON COLUMN slot.code            IS 'Bay number painted on the floor, e.g. B-A-07. UNIQUE within its zone.';
COMMENT ON COLUMN slot.vehicle_type_id IS 'What this bay is built for. Half of the composite key that makes business rule 2 structural.';
COMMENT ON COLUMN slot.is_active       IS 'FALSE = out of service. fn_allocate_slot never returns an inactive bay.';
COMMENT ON COLUMN slot.grid_row        IS 'Position on the floor plan, so the map renders as a plan rather than a list.';
COMMENT ON COLUMN slot.grid_col        IS 'Position on the floor plan. NULL where a bay has no mapped position.';

-- ----------------------------------------------------------------- vehicle_type
COMMENT ON COLUMN vehicle_type.code            IS 'Short uppercase key: CAR, BIKE, SUV, EV, TRUCK.';
COMMENT ON COLUMN vehicle_type.footprint_units IS 'Relative bay size, 1-4. Drives the footprint drawn on the map.';

-- --------------------------------------------------------------------- app_user
COMMENT ON COLUMN app_user.user_id       IS 'Surrogate key. Supplied to the database each request as app.current_user_id, which every RLS policy reads.';
COMMENT ON COLUMN app_user.email         IS 'Login identity. CITEXT, so case does not create a second account.';
COMMENT ON COLUMN app_user.password_hash IS 'bcrypt hash, cost 12. No plaintext password is ever stored or logged.';
COMMENT ON COLUMN app_user.role          IS 'admin | operator | customer. The API also SET ROLEs into the matching database role, and fn_current_role() reads that rather than this column.';
COMMENT ON COLUMN app_user.is_active     IS 'FALSE blocks sign-in without deleting the audit trail on sessions and payments.';

-- --------------------------------------------------------------------- customer
COMMENT ON COLUMN customer.user_id   IS 'Login, if the customer has one. NULL for a walk-in recorded at the gate.';
COMMENT ON COLUMN customer.phone     IS 'Ten digits, no country code. UNIQUE, and the operator search key.';
COMMENT ON COLUMN customer.email     IS 'Optional. CITEXT and UNIQUE.';

-- ---------------------------------------------------------------------- vehicle
COMMENT ON COLUMN vehicle.plate_number    IS 'Registration, uppercase and unspaced, e.g. TS09AB1234. UNIQUE, indexed, and the primary lookup at the gate.';
COMMENT ON COLUMN vehicle.vehicle_type_id IS 'What this vehicle is. The other half of the composite key behind business rule 2.';
COMMENT ON COLUMN vehicle.customer_id     IS 'Owner. ON DELETE RESTRICT: a vehicle with parking history cannot vanish with its owner.';

-- ----------------------------------------------------------------------- tariff
COMMENT ON COLUMN tariff.free_minutes         IS 'Grace period. Leaving within this many minutes costs nothing.';
COMMENT ON COLUMN tariff.first_hour_rate      IS 'Charge for the first chargeable hour, usually dearer than later hours.';
COMMENT ON COLUMN tariff.subsequent_hour_rate IS 'Charge for each hour after the first.';
COMMENT ON COLUMN tariff.daily_cap            IS 'Maximum charge per 24 hours, so an overnight stay cannot run away.';
COMMENT ON COLUMN tariff.effective_from       IS 'Start of this price list. fn_calculate_charge picks the row covering the session entry_time.';
COMMENT ON COLUMN tariff.effective_to         IS 'End of this price list; NULL means in force. Superseding a tariff closes the old row rather than overwriting it, so old bills stay reproducible.';

-- -------------------------------------------------------------------- pass_type
COMMENT ON COLUMN pass_type.duration_days IS 'How long a pass of this product runs from its start date.';
COMMENT ON COLUMN pass_type.price         IS 'Current shelf price. What a customer actually paid is parking_pass.price_paid.';

-- ----------------------------------------------------------------- parking_pass
COMMENT ON COLUMN parking_pass.valid_from   IS 'Start of cover. A session entering inside the window bills at zero.';
COMMENT ON COLUMN parking_pass.valid_to     IS 'End of cover, exclusive.';
COMMENT ON COLUMN parking_pass.price_paid   IS 'What this customer was charged. Deliberately NOT a copy of pass_type.price: the two must diverge when the shelf price changes. See NORMALIZATION.md section 5.';
COMMENT ON COLUMN parking_pass.cancelled_at IS 'Set on cancellation. Stored because cancellation is an event that cannot be inferred from the dates; active/expired state IS inferred.';

-- ------------------------------------------------------------------ reservation
COMMENT ON COLUMN reservation.reserved_from  IS 'Start of the hold. The bay is blocked for the whole window.';
COMMENT ON COLUMN reservation.reserved_until IS 'End of the hold. Must be later than reserved_from (business rule 4).';
COMMENT ON COLUMN reservation.status         IS 'held and confirmed block the bay and participate in ex_reservation_no_overlap; expired, cancelled and fulfilled are history and do not.';

-- -------------------------------------------------------------- parking_session
COMMENT ON COLUMN parking_session.session_id        IS 'Surrogate key.';
COMMENT ON COLUMN parking_session.ticket_no         IS 'Printed ticket reference, TK- plus 8 hex characters. UNIQUE, and one of the two gate lookup keys.';
COMMENT ON COLUMN parking_session.vehicle_type_id   IS 'Carried so the two composite foreign keys can compare the bay type against the vehicle type. Pinned to both simultaneously, so it cannot drift. See NORMALIZATION.md section 5.';
COMMENT ON COLUMN parking_session.entry_time        IS 'Arrival. Also selects which tariff applies.';
COMMENT ON COLUMN parking_session.exit_time         IS 'Departure. NULL means still parked - this column IS the session status, which is why no status column exists.';
COMMENT ON COLUMN parking_session.reservation_id    IS 'The booking this arrival fulfilled, if any. UNIQUE: a reservation is fulfilled at most once.';
COMMENT ON COLUMN parking_session.pass_id           IS 'The pass covering this stay, if any. When set, fn_calculate_charge returns zero.';
COMMENT ON COLUMN parking_session.entry_operator_id IS 'Who admitted the vehicle. SET NULL on staff deletion so the session survives.';
COMMENT ON COLUMN parking_session.exit_operator_id  IS 'Who released the bay.';

-- ------------------------------------------------------------------------- bill
COMMENT ON COLUMN bill.session_id       IS 'UNIQUE: exactly one bill per session.';
COMMENT ON COLUMN bill.tariff_id        IS 'The price list this figure came from. ON DELETE RESTRICT so an old bill stays explainable.';
COMMENT ON COLUMN bill.billable_minutes IS 'Minutes parked, written by trg_bill_enforce_amounts.';
COMMENT ON COLUMN bill.base_amount      IS 'Parking charge. Whatever a client sends is DISCARDED and replaced with fn_calculate_charge(session_id) by trigger - business rule 5.';
COMMENT ON COLUMN bill.tax_amount       IS 'base_amount times the facility tax rate, computed by the same trigger.';
COMMENT ON COLUMN bill.total_amount     IS 'GENERATED ALWAYS AS (base_amount + tax_amount) STORED, so the arithmetic cannot be wrong.';
COMMENT ON COLUMN bill.status           IS 'Derived from the sum of payments by trg_payment_sync_bill_status; never set directly, so a bill cannot read paid with no money behind it.';

-- ---------------------------------------------------------------------- payment
COMMENT ON COLUMN payment.amount       IS 'Money received. CHECK > 0. Several payments may settle one bill, giving partly_paid.';
COMMENT ON COLUMN payment.method       IS 'How it was taken. Recorded only - no gateway is integrated.';
COMMENT ON COLUMN payment.reference_no IS 'Free-text receipt or terminal reference. NEVER a card number, CVV or UPI credential: none are collected anywhere in this system.';
COMMENT ON COLUMN payment.received_by  IS 'Operator who took the payment.';

-- -------------------------------------------------------------------- violation
COMMENT ON COLUMN violation.kind           IS 'overstay | wrong_slot_type | no_valid_pass | unpaid_exit | reservation_no_show.';
COMMENT ON COLUMN violation.session_id     IS 'The stay it arose from, where there was one.';
COMMENT ON COLUMN violation.detected_at    IS 'When it was noticed. Overstays are logged automatically by fn_gate_exit.';
COMMENT ON COLUMN violation.penalty_amount IS 'Fine levied. Zero where the violation is recorded but not charged for.';
COMMENT ON COLUMN violation.resolved_at    IS 'NULL while outstanding. Must not precede detected_at.';
